name: dobx_ds
version: 0.1.0
author: dyu <davidyu@cebu.io>
description: dobx lib for protostuffdb
homepage: https://github.com/dobx/dobx_ds

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  dobx: ^0.7.0

dev_dependencies:
  flutter:
    sdk: flutter

