name: dobx_ds
version: 0.5.0
author: dyu <davidyu@cebu.io>
description: dobx lib for protostuffdb
homepage: https://github.com/dobx/dobx_ds

environment:
  sdk: '>=1.22.0 <2.0.0'

dependencies:
  http: ^0.11.3
  dobx: ^0.7.0
  dobx_gen: ^0.2.0

dev_dependencies:
  build_runner: ^0.3.0+1
  flutter:
    sdk: flutter

