// Generated by fbsgen from p/ds/prk/p4

import '../ds.dart' as ds;


/// message P444441 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required uint32 p4 = 5;
///   required ds.P1 l = 6;
/// }
class P444441 {
  static P444441 create(
    int p0, int p1, int p2, int p3, int p4, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (p4 != null);
    assert (l != null);
    return new P444441()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._p4 = p4
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  int _p4;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  int get p4 => _p4;
  void set p4(int p4) { _p4 = p4; }

  /// required: 6
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P444444 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required uint32 p4 = 5;
///   required ds.P4 l = 6;
/// }
class P444444 {
  static P444444 create(
    int p0, int p1, int p2, int p3, int p4, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (p4 != null);
    assert (l != null);
    return new P444444()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._p4 = p4
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  int _p4;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  int get p4 => _p4;
  void set p4(int p4) { _p4 = p4; }

  /// required: 6
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P444448 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required uint32 p4 = 5;
///   required ds.P8 l = 6;
/// }
class P444448 {
  static P444448 create(
    int p0, int p1, int p2, int p3, int p4, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (p4 != null);
    assert (l != null);
    return new P444448()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._p4 = p4
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  int _p4;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  int get p4 => _p4;
  void set p4(int p4) { _p4 = p4; }

  /// required: 6
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P44444D {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required uint32 p4 = 5;
///   required ds.PD l = 6;
/// }
class P44444D {
  static P44444D create(
    int p0, int p1, int p2, int p3, int p4, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (p4 != null);
    assert (l != null);
    return new P44444D()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._p4 = p4
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  int _p4;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  int get p4 => _p4;
  void set p4(int p4) { _p4 = p4; }

  /// required: 6
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P44444K {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required uint32 p4 = 5;
///   required ds.PK l = 6;
/// }
class P44444K {
  static P44444K create(
    int p0, int p1, int p2, int p3, int p4, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (p4 != null);
    assert (l != null);
    return new P44444K()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._p4 = p4
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  int _p4;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  int get p4 => _p4;
  void set p4(int p4) { _p4 = p4; }

  /// required: 6
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P44444S {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required uint32 p4 = 5;
///   required ds.PS l = 6;
/// }
class P44444S {
  static P44444S create(
    int p0, int p1, int p2, int p3, int p4, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (p4 != null);
    assert (l != null);
    return new P44444S()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._p4 = p4
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  int _p4;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  int get p4 => _p4;
  void set p4(int p4) { _p4 = p4; }

  /// required: 6
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P44441 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required ds.P1 l = 5;
/// }
class P44441 {
  static P44441 create(
    int p0, int p1, int p2, int p3, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new P44441()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P44444 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required ds.P4 l = 5;
/// }
class P44444 {
  static P44444 create(
    int p0, int p1, int p2, int p3, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new P44444()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P44448 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required ds.P8 l = 5;
/// }
class P44448 {
  static P44448 create(
    int p0, int p1, int p2, int p3, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new P44448()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P4444D {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required ds.PD l = 5;
/// }
class P4444D {
  static P4444D create(
    int p0, int p1, int p2, int p3, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new P4444D()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P4444K {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required ds.PK l = 5;
/// }
class P4444K {
  static P4444K create(
    int p0, int p1, int p2, int p3, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new P4444K()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P4444S {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required uint32 p3 = 4;
///   required ds.PS l = 5;
/// }
class P4444S {
  static P4444S create(
    int p0, int p1, int p2, int p3, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new P4444S()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P4441 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required ds.P1 l = 4;
/// }
class P4441 {
  static P4441 create(
    int p0, int p1, int p2, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new P4441()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P4444 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required ds.P4 l = 4;
/// }
class P4444 {
  static P4444 create(
    int p0, int p1, int p2, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new P4444()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P4448 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required ds.P8 l = 4;
/// }
class P4448 {
  static P4448 create(
    int p0, int p1, int p2, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new P4448()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P444D {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required ds.PD l = 4;
/// }
class P444D {
  static P444D create(
    int p0, int p1, int p2, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new P444D()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P444K {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required ds.PK l = 4;
/// }
class P444K {
  static P444K create(
    int p0, int p1, int p2, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new P444K()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P444S {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required uint32 p2 = 3;
///   required ds.PS l = 4;
/// }
class P444S {
  static P444S create(
    int p0, int p1, int p2, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new P444S()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  int _p0;
  int _p1;
  int _p2;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P411 {
///   required uint32 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P411 {
  static P411 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P411()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P414 {
///   required uint32 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P414 {
  static P414 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P414()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P418 {
///   required uint32 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P418 {
  static P418 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P418()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P41D {
///   required uint32 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PD l = 3;
/// }
class P41D {
  static P41D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P41D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P41K {
///   required uint32 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PK l = 3;
/// }
class P41K {
  static P41K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P41K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P41S {
///   required uint32 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PS l = 3;
/// }
class P41S {
  static P41S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P41S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P481 {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P481 {
  static P481 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P481()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P484 {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P484 {
  static P484 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P484()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P488 {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P488 {
  static P488 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P488()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P48D {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class P48D {
  static P48D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P48D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P48K {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class P48K {
  static P48K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P48K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P48S {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class P48S {
  static P48S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P48S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P4D1 {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P4D1 {
  static P4D1 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4D1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P4D4 {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P4D4 {
  static P4D4 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4D4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P4D8 {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P4D8 {
  static P4D8 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4D8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P4DD {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class P4DD {
  static P4DD create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4DD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P4DK {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class P4DK {
  static P4DK create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4DK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P4DS {
///   required uint32 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class P4DS {
  static P4DS create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4DS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P4K1 {
///   required uint32 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P1 l = 3;
/// }
class P4K1 {
  static P4K1 create(
    int p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4K1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P4K4 {
///   required uint32 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P4 l = 3;
/// }
class P4K4 {
  static P4K4 create(
    int p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4K4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P4K8 {
///   required uint32 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P8 l = 3;
/// }
class P4K8 {
  static P4K8 create(
    int p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4K8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P4KD {
///   required uint32 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PD l = 3;
/// }
class P4KD {
  static P4KD create(
    int p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4KD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P4KK {
///   required uint32 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PK l = 3;
/// }
class P4KK {
  static P4KK create(
    int p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4KK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P4KS {
///   required uint32 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PS l = 3;
/// }
class P4KS {
  static P4KS create(
    int p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4KS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P441 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P441 {
  static P441 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P441()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P444 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P444 {
  static P444 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P444()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P448 {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P448 {
  static P448 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P448()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P44D {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PD l = 3;
/// }
class P44D {
  static P44D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P44D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P44K {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PK l = 3;
/// }
class P44K {
  static P44K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P44K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P44S {
///   required uint32 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PS l = 3;
/// }
class P44S {
  static P44S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P44S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P4S1 {
///   required uint32 p0 = 1;
///   required string p1 = 2;
///   required ds.P1 l = 3;
/// }
class P4S1 {
  static P4S1 create(
    int p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4S1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P4S4 {
///   required uint32 p0 = 1;
///   required string p1 = 2;
///   required ds.P4 l = 3;
/// }
class P4S4 {
  static P4S4 create(
    int p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4S4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P4S8 {
///   required uint32 p0 = 1;
///   required string p1 = 2;
///   required ds.P8 l = 3;
/// }
class P4S8 {
  static P4S8 create(
    int p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4S8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P4SD {
///   required uint32 p0 = 1;
///   required string p1 = 2;
///   required ds.PD l = 3;
/// }
class P4SD {
  static P4SD create(
    int p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4SD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P4SK {
///   required uint32 p0 = 1;
///   required string p1 = 2;
///   required ds.PK l = 3;
/// }
class P4SK {
  static P4SK create(
    int p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4SK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P4SS {
///   required uint32 p0 = 1;
///   required string p1 = 2;
///   required ds.PS l = 3;
/// }
class P4SS {
  static P4SS create(
    int p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P4SS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P41 {
///   required uint32 p0 = 1;
///   required ds.P1 l = 2;
/// }
class P41 {
  static P41 create(
    int p0, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P41()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P44 {
///   required uint32 p0 = 1;
///   required ds.P4 l = 2;
/// }
class P44 {
  static P44 create(
    int p0, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P44()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P48 {
///   required uint32 p0 = 1;
///   required ds.P8 l = 2;
/// }
class P48 {
  static P48 create(
    int p0, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P48()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P4D {
///   required uint32 p0 = 1;
///   required ds.PD l = 2;
/// }
class P4D {
  static P4D create(
    int p0, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P4D()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P4K {
///   required uint32 p0 = 1;
///   required ds.PK l = 2;
/// }
class P4K {
  static P4K create(
    int p0, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P4K()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P4S {
///   required uint32 p0 = 1;
///   required ds.PS l = 2;
/// }
class P4S {
  static P4S create(
    int p0, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P4S()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}


