// Generated by fbsgen from p/ds/prk/p8

import '../ds.dart' as ds;


/// message P881 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P881 {
  static P881 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P881()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P884 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P884 {
  static P884 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P884()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P888 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P888 {
  static P888 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P888()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P88D {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class P88D {
  static P88D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P88D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P88K {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class P88K {
  static P88K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P88K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P88S {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class P88S {
  static P88S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P88S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P811 {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P811 {
  static P811 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P811()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P814 {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P814 {
  static P814 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P814()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P818 {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P818 {
  static P818 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P818()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P81D {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PD l = 3;
/// }
class P81D {
  static P81D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P81D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P81K {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PK l = 3;
/// }
class P81K {
  static P81K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P81K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P81S {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PS l = 3;
/// }
class P81S {
  static P81S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P81S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P841 {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P841 {
  static P841 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P841()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P844 {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P844 {
  static P844 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P844()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P848 {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P848 {
  static P848 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P848()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P84D {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PD l = 3;
/// }
class P84D {
  static P84D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P84D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P84K {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PK l = 3;
/// }
class P84K {
  static P84K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P84K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P84S {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PS l = 3;
/// }
class P84S {
  static P84S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P84S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P81 {
///   required uint64 p0 = 1;
///   required ds.P1 l = 2;
/// }
class P81 {
  static P81 create(
    int p0, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P81()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P84 {
///   required uint64 p0 = 1;
///   required ds.P4 l = 2;
/// }
class P84 {
  static P84 create(
    int p0, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P84()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P88 {
///   required uint64 p0 = 1;
///   required ds.P8 l = 2;
/// }
class P88 {
  static P88 create(
    int p0, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P88()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P8D {
///   required uint64 p0 = 1;
///   required ds.PD l = 2;
/// }
class P8D {
  static P8D create(
    int p0, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P8D()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P8K {
///   required uint64 p0 = 1;
///   required ds.PK l = 2;
/// }
class P8K {
  static P8K create(
    int p0, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P8K()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P8S {
///   required uint64 p0 = 1;
///   required ds.PS l = 2;
/// }
class P8S {
  static P8S create(
    int p0, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new P8S()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P8S1 {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.P1 l = 3;
/// }
class P8S1 {
  static P8S1 create(
    int p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8S1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P8S4 {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.P4 l = 3;
/// }
class P8S4 {
  static P8S4 create(
    int p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8S4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P8S8 {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.P8 l = 3;
/// }
class P8S8 {
  static P8S8 create(
    int p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8S8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P8SD {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.PD l = 3;
/// }
class P8SD {
  static P8SD create(
    int p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8SD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P8SK {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.PK l = 3;
/// }
class P8SK {
  static P8SK create(
    int p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8SK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P8SS {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.PS l = 3;
/// }
class P8SS {
  static P8SS create(
    int p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8SS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P8D1 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class P8D1 {
  static P8D1 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8D1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P8D4 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class P8D4 {
  static P8D4 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8D4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P8D8 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class P8D8 {
  static P8D8 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8D8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P8DD {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class P8DD {
  static P8DD create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8DD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P8DK {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class P8DK {
  static P8DK create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8DK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P8DS {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class P8DS {
  static P8DS create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8DS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message P8K1 {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P1 l = 3;
/// }
class P8K1 {
  static P8K1 create(
    int p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8K1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message P8K4 {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P4 l = 3;
/// }
class P8K4 {
  static P8K4 create(
    int p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8K4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message P8K8 {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P8 l = 3;
/// }
class P8K8 {
  static P8K8 create(
    int p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8K8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message P8KD {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PD l = 3;
/// }
class P8KD {
  static P8KD create(
    int p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8KD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message P8KK {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PK l = 3;
/// }
class P8KK {
  static P8KK create(
    int p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8KK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message P8KS {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PS l = 3;
/// }
class P8KS {
  static P8KS create(
    int p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new P8KS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}


