// Generated by fbsgen from p/ds/prk/pd

import '../ds.dart' as ds;


/// message PDD1 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PDD1 {
  static PDD1 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDD1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PDD4 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PDD4 {
  static PDD4 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDD4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PDD8 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PDD8 {
  static PDD8 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDD8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PDDD {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class PDDD {
  static PDDD create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDDD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PDDK {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class PDDK {
  static PDDK create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDDK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PDDS {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class PDDS {
  static PDDS create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDDS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PDS1 {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.P1 l = 3;
/// }
class PDS1 {
  static PDS1 create(
    int p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDS1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PDS4 {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.P4 l = 3;
/// }
class PDS4 {
  static PDS4 create(
    int p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDS4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PDS8 {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.P8 l = 3;
/// }
class PDS8 {
  static PDS8 create(
    int p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDS8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PDSD {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.PD l = 3;
/// }
class PDSD {
  static PDSD create(
    int p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDSD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PDSK {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.PK l = 3;
/// }
class PDSK {
  static PDSK create(
    int p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDSK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PDSS {
///   required uint64 p0 = 1;
///   required string p1 = 2;
///   required ds.PS l = 3;
/// }
class PDSS {
  static PDSS create(
    int p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDSS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PD1 {
///   required uint64 p0 = 1;
///   required ds.P1 l = 2;
/// }
class PD1 {
  static PD1 create(
    int p0, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PD1()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PD4 {
///   required uint64 p0 = 1;
///   required ds.P4 l = 2;
/// }
class PD4 {
  static PD4 create(
    int p0, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PD4()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PD8 {
///   required uint64 p0 = 1;
///   required ds.P8 l = 2;
/// }
class PD8 {
  static PD8 create(
    int p0, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PD8()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PDD {
///   required uint64 p0 = 1;
///   required ds.PD l = 2;
/// }
class PDD {
  static PDD create(
    int p0, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PDD()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PDK {
///   required uint64 p0 = 1;
///   required ds.PK l = 2;
/// }
class PDK {
  static PDK create(
    int p0, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PDK()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PDS {
///   required uint64 p0 = 1;
///   required ds.PS l = 2;
/// }
class PDS {
  static PDS create(
    int p0, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PDS()
      .._p0 = p0
      .._l = l;
  }
  int _p0;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PDK1 {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P1 l = 3;
/// }
class PDK1 {
  static PDK1 create(
    int p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDK1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PDK4 {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P4 l = 3;
/// }
class PDK4 {
  static PDK4 create(
    int p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDK4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PDK8 {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.P8 l = 3;
/// }
class PDK8 {
  static PDK8 create(
    int p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDK8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PDKD {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PD l = 3;
/// }
class PDKD {
  static PDKD create(
    int p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDKD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PDKK {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PK l = 3;
/// }
class PDKK {
  static PDKK create(
    int p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDKK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PDKS {
///   required uint64 p0 = 1;
///   required bytes p1 = 2;
///   required ds.PS l = 3;
/// }
class PDKS {
  static PDKS create(
    int p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PDKS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PD11 {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PD11 {
  static PD11 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD11()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PD14 {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PD14 {
  static PD14 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD14()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PD18 {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PD18 {
  static PD18 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD18()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PD1D {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PD l = 3;
/// }
class PD1D {
  static PD1D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD1D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PD1K {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PK l = 3;
/// }
class PD1K {
  static PD1K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD1K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PD1S {
///   required uint64 p0 = 1;
///   required int8 p1 = 2;
///   required ds.PS l = 3;
/// }
class PD1S {
  static PD1S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD1S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PD81 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PD81 {
  static PD81 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD81()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PD84 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PD84 {
  static PD84 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD84()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PD88 {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PD88 {
  static PD88 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD88()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PD8D {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class PD8D {
  static PD8D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD8D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PD8K {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class PD8K {
  static PD8K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD8K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PD8S {
///   required uint64 p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class PD8S {
  static PD8S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD8S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PD41 {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PD41 {
  static PD41 create(
    int p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD41()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PD44 {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PD44 {
  static PD44 create(
    int p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD44()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PD48 {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PD48 {
  static PD48 create(
    int p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD48()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PD4D {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PD l = 3;
/// }
class PD4D {
  static PD4D create(
    int p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD4D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PD4K {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PK l = 3;
/// }
class PD4K {
  static PD4K create(
    int p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD4K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PD4S {
///   required uint64 p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PS l = 3;
/// }
class PD4S {
  static PD4S create(
    int p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PD4S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  int _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  int get p0 => _p0;
  void set p0(int p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}


