// Generated by fbsgen from p/ds/prk/pk

import '../ds.dart' as ds;


/// message PK111 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.P1 l = 4;
/// }
class PK111 {
  static PK111 create(
    String p0, int p1, int p2, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PK111()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PK114 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.P4 l = 4;
/// }
class PK114 {
  static PK114 create(
    String p0, int p1, int p2, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PK114()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PK118 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.P8 l = 4;
/// }
class PK118 {
  static PK118 create(
    String p0, int p1, int p2, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PK118()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PK11D {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.PD l = 4;
/// }
class PK11D {
  static PK11D create(
    String p0, int p1, int p2, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PK11D()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PK11K {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.PK l = 4;
/// }
class PK11K {
  static PK11K create(
    String p0, int p1, int p2, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PK11K()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PK11S {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.PS l = 4;
/// }
class PK11S {
  static PK11S create(
    String p0, int p1, int p2, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PK11S()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PK81 {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PK81 {
  static PK81 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK81()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PK84 {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PK84 {
  static PK84 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK84()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PK88 {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PK88 {
  static PK88 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK88()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PK8D {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class PK8D {
  static PK8D create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK8D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PK8K {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class PK8K {
  static PK8K create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK8K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PK8S {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class PK8S {
  static PK8S create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK8S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PK1111 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required int8 p3 = 4;
///   required ds.P1 l = 5;
/// }
class PK1111 {
  static PK1111 create(
    String p0, int p1, int p2, int p3, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new PK1111()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PK1114 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required int8 p3 = 4;
///   required ds.P4 l = 5;
/// }
class PK1114 {
  static PK1114 create(
    String p0, int p1, int p2, int p3, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new PK1114()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PK1118 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required int8 p3 = 4;
///   required ds.P8 l = 5;
/// }
class PK1118 {
  static PK1118 create(
    String p0, int p1, int p2, int p3, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new PK1118()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PK111D {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required int8 p3 = 4;
///   required ds.PD l = 5;
/// }
class PK111D {
  static PK111D create(
    String p0, int p1, int p2, int p3, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new PK111D()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PK111K {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required int8 p3 = 4;
///   required ds.PK l = 5;
/// }
class PK111K {
  static PK111K create(
    String p0, int p1, int p2, int p3, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new PK111K()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PK111S {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required int8 p3 = 4;
///   required ds.PS l = 5;
/// }
class PK111S {
  static PK111S create(
    String p0, int p1, int p2, int p3, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (p3 != null);
    assert (l != null);
    return new PK111S()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._p3 = p3
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  int _p3;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  int get p3 => _p3;
  void set p3(int p3) { _p3 = p3; }

  /// required: 5
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PK11 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PK11 {
  static PK11 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK11()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PK14 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PK14 {
  static PK14 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK14()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PK18 {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PK18 {
  static PK18 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK18()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PK1D {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required ds.PD l = 3;
/// }
class PK1D {
  static PK1D create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK1D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PK1K {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required ds.PK l = 3;
/// }
class PK1K {
  static PK1K create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK1K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PK1S {
///   required bytes p0 = 1;
///   required int8 p1 = 2;
///   required ds.PS l = 3;
/// }
class PK1S {
  static PK1S create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK1S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PKK1 {
///   required bytes p0 = 1;
///   required bytes p1 = 2;
///   required ds.P1 l = 3;
/// }
class PKK1 {
  static PKK1 create(
    String p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKK1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PKK4 {
///   required bytes p0 = 1;
///   required bytes p1 = 2;
///   required ds.P4 l = 3;
/// }
class PKK4 {
  static PKK4 create(
    String p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKK4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PKK8 {
///   required bytes p0 = 1;
///   required bytes p1 = 2;
///   required ds.P8 l = 3;
/// }
class PKK8 {
  static PKK8 create(
    String p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKK8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PKKD {
///   required bytes p0 = 1;
///   required bytes p1 = 2;
///   required ds.PD l = 3;
/// }
class PKKD {
  static PKKD create(
    String p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKKD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PKKK {
///   required bytes p0 = 1;
///   required bytes p1 = 2;
///   required ds.PK l = 3;
/// }
class PKKK {
  static PKKK create(
    String p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKKK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PKKS {
///   required bytes p0 = 1;
///   required bytes p1 = 2;
///   required ds.PS l = 3;
/// }
class PKKS {
  static PKKS create(
    String p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKKS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PK1 {
///   required bytes p0 = 1;
///   required ds.P1 l = 2;
/// }
class PK1 {
  static PK1 create(
    String p0, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PK1()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PK4 {
///   required bytes p0 = 1;
///   required ds.P4 l = 2;
/// }
class PK4 {
  static PK4 create(
    String p0, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PK4()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PK8 {
///   required bytes p0 = 1;
///   required ds.P8 l = 2;
/// }
class PK8 {
  static PK8 create(
    String p0, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PK8()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PKD {
///   required bytes p0 = 1;
///   required ds.PD l = 2;
/// }
class PKD {
  static PKD create(
    String p0, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PKD()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PKK {
///   required bytes p0 = 1;
///   required ds.PK l = 2;
/// }
class PKK {
  static PKK create(
    String p0, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PKK()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PKS {
///   required bytes p0 = 1;
///   required ds.PS l = 2;
/// }
class PKS {
  static PKS create(
    String p0, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PKS()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PKD1 {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PKD1 {
  static PKD1 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKD1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PKD4 {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PKD4 {
  static PKD4 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKD4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PKD8 {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PKD8 {
  static PKD8 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKD8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PKDD {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class PKDD {
  static PKDD create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKDD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PKDK {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class PKDK {
  static PKDK create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKDK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PKDS {
///   required bytes p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class PKDS {
  static PKDS create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKDS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PK41 {
///   required bytes p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PK41 {
  static PK41 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK41()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PK44 {
///   required bytes p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PK44 {
  static PK44 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK44()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PK48 {
///   required bytes p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PK48 {
  static PK48 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK48()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PK4D {
///   required bytes p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PD l = 3;
/// }
class PK4D {
  static PK4D create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK4D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PK4K {
///   required bytes p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PK l = 3;
/// }
class PK4K {
  static PK4K create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK4K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PK4S {
///   required bytes p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PS l = 3;
/// }
class PK4S {
  static PK4S create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PK4S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PKS1 {
///   required bytes p0 = 1;
///   required string p1 = 2;
///   required ds.P1 l = 3;
/// }
class PKS1 {
  static PKS1 create(
    String p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKS1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PKS4 {
///   required bytes p0 = 1;
///   required string p1 = 2;
///   required ds.P4 l = 3;
/// }
class PKS4 {
  static PKS4 create(
    String p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKS4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PKS8 {
///   required bytes p0 = 1;
///   required string p1 = 2;
///   required ds.P8 l = 3;
/// }
class PKS8 {
  static PKS8 create(
    String p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKS8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PKSD {
///   required bytes p0 = 1;
///   required string p1 = 2;
///   required ds.PD l = 3;
/// }
class PKSD {
  static PKSD create(
    String p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKSD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PKSK {
///   required bytes p0 = 1;
///   required string p1 = 2;
///   required ds.PK l = 3;
/// }
class PKSK {
  static PKSK create(
    String p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKSK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PKSS {
///   required bytes p0 = 1;
///   required string p1 = 2;
///   required ds.PS l = 3;
/// }
class PKSS {
  static PKSS create(
    String p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PKSS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}


