// Generated by fbsgen from p/ds/prk/ps

import '../ds.dart' as ds;


/// message PSK1 {
///   required string p0 = 1;
///   required bytes p1 = 2;
///   required ds.P1 l = 3;
/// }
class PSK1 {
  static PSK1 create(
    String p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSK1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PSK4 {
///   required string p0 = 1;
///   required bytes p1 = 2;
///   required ds.P4 l = 3;
/// }
class PSK4 {
  static PSK4 create(
    String p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSK4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PSK8 {
///   required string p0 = 1;
///   required bytes p1 = 2;
///   required ds.P8 l = 3;
/// }
class PSK8 {
  static PSK8 create(
    String p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSK8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PSKD {
///   required string p0 = 1;
///   required bytes p1 = 2;
///   required ds.PD l = 3;
/// }
class PSKD {
  static PSKD create(
    String p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSKD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PSKK {
///   required string p0 = 1;
///   required bytes p1 = 2;
///   required ds.PK l = 3;
/// }
class PSKK {
  static PSKK create(
    String p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSKK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PSKS {
///   required string p0 = 1;
///   required bytes p1 = 2;
///   required ds.PS l = 3;
/// }
class PSKS {
  static PSKS create(
    String p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSKS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PS111 {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.P1 l = 4;
/// }
class PS111 {
  static PS111 create(
    String p0, int p1, int p2, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PS111()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PS114 {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.P4 l = 4;
/// }
class PS114 {
  static PS114 create(
    String p0, int p1, int p2, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PS114()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PS118 {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.P8 l = 4;
/// }
class PS118 {
  static PS118 create(
    String p0, int p1, int p2, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PS118()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PS11D {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.PD l = 4;
/// }
class PS11D {
  static PS11D create(
    String p0, int p1, int p2, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PS11D()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PS11K {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.PK l = 4;
/// }
class PS11K {
  static PS11K create(
    String p0, int p1, int p2, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PS11K()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PS11S {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required int8 p2 = 3;
///   required ds.PS l = 4;
/// }
class PS11S {
  static PS11S create(
    String p0, int p1, int p2, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (p2 != null);
    assert (l != null);
    return new PS11S()
      .._p0 = p0
      .._p1 = p1
      .._p2 = p2
      .._l = l;
  }
  String _p0;
  int _p1;
  int _p2;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  int get p2 => _p2;
  void set p2(int p2) { _p2 = p2; }

  /// required: 4
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PSD1 {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PSD1 {
  static PSD1 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSD1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PSD4 {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PSD4 {
  static PSD4 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSD4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PSD8 {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PSD8 {
  static PSD8 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSD8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PSDD {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class PSDD {
  static PSDD create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSDD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PSDK {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class PSDK {
  static PSDK create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSDK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PSDS {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class PSDS {
  static PSDS create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSDS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PS41 {
///   required string p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PS41 {
  static PS41 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS41()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PS44 {
///   required string p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PS44 {
  static PS44 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS44()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PS48 {
///   required string p0 = 1;
///   required uint32 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PS48 {
  static PS48 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS48()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PS4D {
///   required string p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PD l = 3;
/// }
class PS4D {
  static PS4D create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS4D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PS4K {
///   required string p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PK l = 3;
/// }
class PS4K {
  static PS4K create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS4K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PS4S {
///   required string p0 = 1;
///   required uint32 p1 = 2;
///   required ds.PS l = 3;
/// }
class PS4S {
  static PS4S create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS4S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PSS1 {
///   required string p0 = 1;
///   required string p1 = 2;
///   required ds.P1 l = 3;
/// }
class PSS1 {
  static PSS1 create(
    String p0, String p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSS1()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PSS4 {
///   required string p0 = 1;
///   required string p1 = 2;
///   required ds.P4 l = 3;
/// }
class PSS4 {
  static PSS4 create(
    String p0, String p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSS4()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PSS8 {
///   required string p0 = 1;
///   required string p1 = 2;
///   required ds.P8 l = 3;
/// }
class PSS8 {
  static PSS8 create(
    String p0, String p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSS8()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PSSD {
///   required string p0 = 1;
///   required string p1 = 2;
///   required ds.PD l = 3;
/// }
class PSSD {
  static PSSD create(
    String p0, String p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSSD()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PSSK {
///   required string p0 = 1;
///   required string p1 = 2;
///   required ds.PK l = 3;
/// }
class PSSK {
  static PSSK create(
    String p0, String p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSSK()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PSSS {
///   required string p0 = 1;
///   required string p1 = 2;
///   required ds.PS l = 3;
/// }
class PSSS {
  static PSSS create(
    String p0, String p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PSSS()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  String _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  String get p1 => _p1;
  void set p1(String p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PS11 {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PS11 {
  static PS11 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS11()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PS14 {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PS14 {
  static PS14 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS14()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PS18 {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PS18 {
  static PS18 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS18()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PS1D {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required ds.PD l = 3;
/// }
class PS1D {
  static PS1D create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS1D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PS1K {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required ds.PK l = 3;
/// }
class PS1K {
  static PS1K create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS1K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PS1S {
///   required string p0 = 1;
///   required int8 p1 = 2;
///   required ds.PS l = 3;
/// }
class PS1S {
  static PS1S create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS1S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PS81 {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P1 l = 3;
/// }
class PS81 {
  static PS81 create(
    String p0, int p1, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS81()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PS84 {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P4 l = 3;
/// }
class PS84 {
  static PS84 create(
    String p0, int p1, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS84()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PS88 {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.P8 l = 3;
/// }
class PS88 {
  static PS88 create(
    String p0, int p1, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS88()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PS8D {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PD l = 3;
/// }
class PS8D {
  static PS8D create(
    String p0, int p1, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS8D()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PS8K {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PK l = 3;
/// }
class PS8K {
  static PS8K create(
    String p0, int p1, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS8K()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PS8S {
///   required string p0 = 1;
///   required uint64 p1 = 2;
///   required ds.PS l = 3;
/// }
class PS8S {
  static PS8S create(
    String p0, int p1, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (p1 != null);
    assert (l != null);
    return new PS8S()
      .._p0 = p0
      .._p1 = p1
      .._l = l;
  }
  String _p0;
  int _p1;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  int get p1 => _p1;
  void set p1(int p1) { _p1 = p1; }

  /// required: 3
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}



/// message PS1 {
///   required string p0 = 1;
///   required ds.P1 l = 2;
/// }
class PS1 {
  static PS1 create(
    String p0, ds.P1 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PS1()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.P1 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.P1 get l => _l;
  void set l(ds.P1 l) { _l = l; }
}



/// message PS4 {
///   required string p0 = 1;
///   required ds.P4 l = 2;
/// }
class PS4 {
  static PS4 create(
    String p0, ds.P4 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PS4()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.P4 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.P4 get l => _l;
  void set l(ds.P4 l) { _l = l; }
}



/// message PS8 {
///   required string p0 = 1;
///   required ds.P8 l = 2;
/// }
class PS8 {
  static PS8 create(
    String p0, ds.P8 l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PS8()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.P8 _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.P8 get l => _l;
  void set l(ds.P8 l) { _l = l; }
}



/// message PSD {
///   required string p0 = 1;
///   required ds.PD l = 2;
/// }
class PSD {
  static PSD create(
    String p0, ds.PD l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PSD()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.PD _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.PD get l => _l;
  void set l(ds.PD l) { _l = l; }
}



/// message PSK {
///   required string p0 = 1;
///   required ds.PK l = 2;
/// }
class PSK {
  static PSK create(
    String p0, ds.PK l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PSK()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.PK _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.PK get l => _l;
  void set l(ds.PK l) { _l = l; }
}



/// message PSS {
///   required string p0 = 1;
///   required ds.PS l = 2;
/// }
class PSS {
  static PSS create(
    String p0, ds.PS l, 
  ) {
    assert (p0 != null);
    assert (l != null);
    return new PSS()
      .._p0 = p0
      .._l = l;
  }
  String _p0;
  ds.PS _l;

  /// required: 1
  String get p0 => _p0;
  void set p0(String p0) { _p0 = p0; }

  /// required: 2
  ds.PS get l => _l;
  void set l(ds.PS l) { _l = l; }
}


